### ISSUE TITLE
希望添加表结构初始化SQL

### ISSUE THREAD

**Issue by zk-robin** [lingdu1234/axum_admin#13]
只看到表数据初始化插入的sql，没有看到表结构sql

**Comment by lingdu1234** [comment]
表结构初始化是通过`entity`来实现的，没有通过sql语句，详细见[db_utils.rs](https://github.com/lingdu1234/axum_admin/blob/axum/migration/src/db_utils.rs) 的 `create_one_table` 函数

Table structure initialization is implemented through entities, rather than SQL statements. See the `create_one_table`  function in the [db_utils.rs](https://github.com/lingdu1234/axum_admin/blob/axum/migration/src/db_utils.rs) file for details.
